import {monday,addDays,formatDate} from './calendar.js?v=0.3.7';
export const quadrant=t=>t.importance==='high'?(t.effort==='high'?'anchor':'wins'):(t.effort==='high'?'drains':'sparks');
export function activeAnchor(tasks,week){return tasks.find(t=>t.matrixWeek===week&&!t.deleted&&!t.done&&quadrant(t)==='anchor'&&t.anchorActive);}
export function activateAnchor(tasks,t){if(activeAnchor(tasks,t.matrixWeek)&&activeAnchor(tasks,t.matrixWeek)!==t)return false;t.anchorActive=true;return true;}
export function createMatrix({getState,getDate,save,render,esc,id,openModal,closeModal,toast}){
 const items=()=>getState().tasks.filter(t=>t.matrixWeek===monday(getDate())&&!t.deleted);
 const find=k=>getState().tasks.find(t=>t.id===k);
 const row=(t,step=null)=>{const key=step?.id||'',done=step?step.done:t.done;return `<div class="matrix-task ${done?'done':''}" draggable="${!done}" data-matrix-drag="${esc(t.id)}" data-matrix-step="${esc(key)}"><label><input type="checkbox" data-matrix-check="${esc(t.id)}" data-step="${esc(key)}" ${done?'checked':''}> ${esc(step?.title||t.title)}</label>${!done?`<button type="button" data-matrix-schedule="${esc(t.id)}" data-step="${esc(key)}">Schedule</button>`:''}${!step?`<button type="button" data-matrix-edit="${esc(t.id)}" aria-label="Edit ${esc(t.title)}">Edit</button>`:''}</div>`;};
 function panel(){const list=items(),anchor=activeAnchor(list,monday(getDate())),waiting=list.filter(t=>quadrant(t)==='anchor'&&t!==anchor&&!t.done),others=list.filter(t=>quadrant(t)!=='anchor'&&quadrant(t)!=='drains');return `<aside class="focus-engine"><details ${getState().settings.matrixCollapsed===false?'open':''} data-matrix-collapse><summary><span class="focus-title">Plan this week</span><span class="focus-preview">${anchor?esc(anchor.title):'Choose your focus, then make time for it'}</span></summary><div class="focus-body"><p class="focus-guide">Add what you want to do and choose its importance and effort. Pick one important, demanding task as your Strategic Anchor. Break it into steps, then use Schedule to choose a day and time, or drag a step into a day’s “Plan a time” slots.</p><div class="matrix-toolbar"><button type="button" class="secondary" data-matrix-add>+ Add tasks</button></div><section class="matrix-anchor"><h2>This week’s anchor</h2>${anchor?row(anchor)+`<div class="anchor-actions"><button type="button" data-matrix-add-step="${esc(anchor.id)}">+ Add a step</button><button type="button" data-matrix-release="${esc(anchor.id)}">Release anchor</button></div>`+(anchor.steps||[]).map(s=>row(anchor,s)).join(''):'<p>One high-importance, high-effort task can be active this week. Add a task with both set to High to choose it.</p>'}${waiting.length?`<details class="focus-secondary"><summary>Waiting anchors (${waiting.length})</summary>${waiting.map(t=>row(t)+`<button type="button" data-matrix-activate="${esc(t.id)}" ${anchor?'disabled':''}>Make active</button>`).join('')}</details>`:''}</section>${others.length?`<section class="focus-other"><h2>Other tasks for this week</h2>${others.map(t=>row(t)).join('')}</section>`:''}${list.some(t=>quadrant(t)==='drains')?`<details class="focus-secondary"><summary>Reconsider these tasks (${list.filter(t=>quadrant(t)==='drains').length})</summary><p>These take high effort but have low importance. Leave them out unless they earn their place.</p>${list.filter(t=>quadrant(t)==='drains').map(t=>row(t)).join('')}</details>`:''}</div></details></aside>`;}

 function drawer(t=null){openModal(t?'Route task':'Rapid task entry',`<form id="matrix-entry" data-id="${t?.id||''}" data-week="${monday(getDate())}"><label>${t?'Task':'Tasks · one per line'}<textarea name="titles" required maxlength="4000" autofocus>${esc(t?.title||'')}</textarea></label><div class="form-grid"><label>Effort<select name="effort"><option value="low">Low</option><option value="high" ${t?.effort==='high'?'selected':''}>High</option></select></label><label>Importance<select name="importance"><option value="high">High</option><option value="low" ${t?.importance==='low'?'selected':''}>Low</option></select></label></div><p>High importance + high effort creates an Anchor. Other tasks stay in your weekly list. Extra anchors wait until the active one is released.</p><button class="primary" type="submit">${t?'Save routing':'Add to this week'}</button></form>`);}
 function schedule(k,step='',day=getDate(),time='09:00'){const t=find(k);if(!t||t.done||t.matrixWeek!==monday(day))return toast('Choose an unfinished task from this week.');if(quadrant(t)==='anchor'&&activeAnchor(getState().tasks,t.matrixWeek)!==t)return toast('Activate this anchor before scheduling it.');const s=t.steps?.find(x=>x.id===step);if(step&&!s)return;openModal('Schedule '+esc(s?.title||t.title),`<form id="matrix-schedule" data-id="${esc(k)}" data-step="${esc(step)}" data-week="${t.matrixWeek}"><div class="form-grid"><label>Day<input name="date" type="date" value="${day}" min="${t.matrixWeek}" max="${addDays(t.matrixWeek,6)}" required></label><label>Time<input name="time" type="time" value="${time}" required></label><label>Minutes<input name="duration" type="number" min="5" max="720" step="5" value="30" required></label></div><button class="primary" type="submit">Pin to calendar</button></form>`);}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if('matrixAdd'in d)drawer();if(d.matrixEdit)drawer(find(d.matrixEdit));if(d.matrixSchedule)schedule(d.matrixSchedule,d.step);if(d.matrixRelease){find(d.matrixRelease).anchorActive=false;save();render();}if(d.matrixActivate){if(!activateAnchor(getState().tasks,find(d.matrixActivate)))return toast('Only one Strategic Anchor can be active this week.');save();render();}if(d.matrixAddStep)openModal('Add an anchor step',`<form id="matrix-step" data-id="${esc(d.matrixAddStep)}"><label>Step<input name="title" type="text" maxlength="200" required autofocus></label><button class="primary" type="submit">Add step</button></form>`);if(d.matrixSlot)scheduleChooser(d.matrixSlot,d.time);});
 function scheduleChooser(day,time){const tasks=items().filter(t=>!t.done&&(quadrant(t)!=='anchor'||activeAnchor(getState().tasks,t.matrixWeek)===t));openModal('Plan '+formatDate(day,{weekday:'long'})+' at '+time,tasks.map(t=>`<button type="button" data-matrix-slot-pick="${esc(t.id)}" data-day="${day}" data-time="${time}">${esc(t.title)}</button>`).join('')||'<p>Add a task to the Weekly Focus Engine first.</p>');}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-matrix-slot-pick]');if(b)schedule(b.dataset.matrixSlotPick,'',b.dataset.day,b.dataset.time);});
 document.addEventListener('change',e=>{const d=e.target.dataset;if(d.matrixCheck){const t=find(d.matrixCheck),s=t.steps?.find(x=>x.id===d.step);if(d.step&&s)s.done=e.target.checked;else{if(!e.target.checked&&quadrant(t)==='anchor'&&t.anchorActive&&activeAnchor(getState().tasks,t.matrixWeek))t.anchorActive=false;t.done=e.target.checked;}save();render();}});
 document.addEventListener('toggle',e=>{if(e.target.matches('[data-matrix-collapse]')){getState().settings.matrixCollapsed=!e.target.open;save();}},true);
 document.addEventListener('dragstart',e=>{const el=e.target.closest('[data-matrix-drag]');if(el)e.dataTransfer.setData('application/x-unbound-task',JSON.stringify({id:el.dataset.matrixDrag,step:el.dataset.matrixStep}));});
 document.addEventListener('dragover',e=>{if(e.target.closest('[data-matrix-slot]')&&[...e.dataTransfer.types].includes('application/x-unbound-task'))e.preventDefault();});
 document.addEventListener('drop',e=>{const slot=e.target.closest('[data-matrix-slot]');if(!slot)return;const raw=e.dataTransfer.getData('application/x-unbound-task');if(!raw)return;e.preventDefault();try{const t=JSON.parse(raw);schedule(t.id,t.step,slot.dataset.matrixSlot,slot.dataset.time);}catch{toast('Could not schedule this task.');}});
 document.addEventListener('submit',e=>{const f=e.target;if(!f.id.startsWith('matrix-'))return;e.preventDefault();const d=Object.fromEntries(new FormData(f)),state=getState();try{
 if(f.id==='matrix-entry'){const titles=d.titles.split('\n').map(x=>x.trim()).filter(Boolean);if(!titles.length)throw Error('Add a task.');if(f.dataset.id){const t=find(f.dataset.id);Object.assign(t,{title:titles.join(' ').slice(0,200),effort:d.effort,importance:d.importance});t.anchorActive=false;if(quadrant(t)==='anchor'&&!t.done)activateAnchor(state.tasks,t);}else titles.forEach(title=>{const t={id:id(),title:title.slice(0,200),date:'',done:false,priority:d.importance==='high'?'important':'later',matrixWeek:f.dataset.week,effort:d.effort,importance:d.importance,steps:[]};if(quadrant(t)==='anchor')activateAnchor(state.tasks,t);state.tasks.push(t);});}
 if(f.id==='matrix-step'){const t=find(f.dataset.id);if(!d.title.trim())throw Error('Name this step.');(t.steps??=[]).push({id:id(),title:d.title.trim(),done:false});}
 if(f.id==='matrix-schedule'){const t=find(f.dataset.id),s=t.steps?.find(x=>x.id===f.dataset.step);if(!t||t.done||s?.done||monday(d.date)!==t.matrixWeek)throw Error('Choose an unfinished task and a day in its week.');if(quadrant(t)==='anchor'&&activeAnchor(state.tasks,t.matrixWeek)!==t)throw Error('Activate this anchor first.');const minutes=Number(d.duration),[h,m]=d.time.split(':').map(Number),end=h*60+m+minutes;if(!d.time||!Number.isFinite(end)||minutes<5||minutes>720||end>=1440)throw Error('Choose a time and duration ending before midnight.');const timeEnd=String(Math.floor(end/60)).padStart(2,'0')+':'+String(end%60).padStart(2,'0');const key=f.dataset.step||'';const old=state.events.find(x=>x.matrixTask===t.id&&x.matrixStep===key);const event={id:old?.id||id(),title:s?.title||t.title,date:d.date,endDate:d.date,lastDate:d.date,time:d.time,endTime:timeEnd,category:'work',repeat:'none',matrixTask:t.id,matrixStep:key};if(old)Object.assign(old,event);else state.events.push(event);if(s){s.date=d.date;s.time=d.time;}else{t.date=d.date;t.time=d.time;}}
 save();closeModal();render();}catch(err){toast(err.message);}});
 return {panel,slots:day=>`<details class="matrix-slots"><summary>Plan a time</summary><div>${Array.from({length:17},(_,i)=>{const time=String(i+6).padStart(2,'0')+':00';return `<button type="button" data-matrix-slot="${day}" data-time="${time}" aria-label="Schedule on ${day} at ${time}">${time}</button>`;}).join('')}</div></details>`};
}
