import test from 'node:test';
import assert from 'node:assert/strict';
import {importRoutine,exportRoutine,gymExercises,newGymSession,validateRoutine,createGymController} from '../gym.js';
const routine=()=>({format:'unbound-gym-routine',version:1,title:'Example routine',exercises:[{name:'Example assisted machine',type:'strength',mode:'assistance',sets:[{weight:'12.5',reps:'8',rest:'90'}]},{name:'Example cardio',type:'cardio',mode:'weight',metric:'Grade',sets:[{duration:'12:30',incline:'3',level:'4'}]}]});
const ids=()=>{let n=0;return ()=>String(++n);};
test('routine import and export preserve strength assistance and machine-specific cardio values without overwriting existing entries',()=>{const entries={other:'keep'},id=ids();importRoutine(entries,'one',routine(),id);assert.equal(entries.other,'keep');assert.ok(Object.values(entries).every(v=>typeof v==='string'));assert.equal(gymExercises(entries,'one')[0].mode,'assistance');assert.equal(gymExercises(entries,'one')[1].sets[0].incline,'3');const exported=exportRoutine(entries,'one');validateRoutine(exported);assert.equal(exported.exercises[1].sets[0].duration,'12:30');assert.throws(()=>importRoutine(entries,'one',routine(),id),/empty gym form/);});
test('new sessions preserve routine settings and previous values while resetting checks',()=>{const entries={'form:one:type':'gym'},id=ids();importRoutine(entries,'one',routine(),id);const exercise=gymExercises(entries,'one')[0];entries[exercise.sets[0].stem+'done']='yes';const before=JSON.stringify(entries);newGymSession(entries,'one','two');const next=gymExercises(entries,'two');assert.equal(next[0].sets[0].done,'no');assert.equal(next[0].sets[0].weight,'12.5');assert.match(next[0].sets[0].previous,/assistance/);assert.equal(JSON.stringify(Object.fromEntries(Object.entries(entries).filter(([k])=>!k.startsWith('form:two:')))),before);});
test('invalid files are rejected before mutating a notebook',()=>{const entries={keep:'writing'};const data=routine();data.exercises[0].sets[0].weight='-20';assert.throws(()=>importRoutine(entries,'one',data,ids()));assert.deepEqual(entries,{keep:'writing'});data.exercises[0].sets[0].weight='20';data.exercises[1].sets[0].duration='12:99';assert.throws(()=>validateRoutine(data),/minutes:seconds/);});
test('adding sets and recording completed sets do not lose cardio settings or load mode',()=>{const entries={},id=ids();importRoutine(entries,'one',routine(),id);let saved=0;const controller=createGymController({entries:()=>entries,form:()=> 'one',esc:String,id,save:()=>saved++,render:()=>{},openModal:()=>{},closeModal:()=>{},toast:()=>{},confirmAction:()=>{}});const exercise=gymExercises(entries,'one')[0];controller.handle({gymAddSet:exercise.id});assert.equal(gymExercises(entries,'one')[0].sets.length,2);assert.equal(gymExercises(entries,'one')[0].sets[1].weight,'12.5');controller.handle({gymDone:exercise.id,gymSet:exercise.sets[0].id});assert.equal(gymExercises(entries,'one')[0].sets[0].done,'yes');assert.ok(controller.render().includes('Assistance kg'));assert.ok(controller.render().includes('Incline %'));assert.equal(saved,2);});
