import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {monday} from '../calendar.js';
import {notebookContent,mergeNotebook} from '../sync.js';
const source=readFileSync(new URL('../app.js',import.meta.url),'utf8');
function harness(){let submit,counter=0;const state={notes:[],tasks:[],events:[],entries:{},ink:{},settings:{}};const errors=[];const context={state,monday,date:'2026-10-07',section:'calendar',view:'week',id:()=>String(++counter),entry:k=>state.entries[k]||'',save(){},closeModal(){},render(){},toast:x=>errors.push(x),FormData:class{constructor(form){return Object.entries(form.values)}},document:{addEventListener(type,handler){submit=handler;}}};vm.createContext(context);const a=source.indexOf("document.addEventListener('submit',async e=>");const z=source.indexOf("document.querySelector('#cover-file').addEventListener",a);vm.runInContext(source.slice(a,z),context);return {state,errors,submit:(id,values,item='')=>submit({preventDefault(){},target:{id,dataset:{id:item},values,querySelector(){return null}}})};}
test('capturing an idea creates no calendar event or task, and survives backup merge',async()=>{const h=harness();await h.submit('idea-capture',{title:'New project',body:'Unstructured thoughts'});assert.equal(h.state.notes[0].ideaStatus,'parked');assert.equal(h.state.tasks.length,0);assert.equal(h.state.events.length,0);const copy=notebookContent(h.state);assert.equal(copy.entries['note:1'],'Unstructured thoughts');const merged=mergeNotebook(copy,copy,copy);assert.equal(merged.data.notes[0].idea,true);});
test('ignite respects the active anchor and preserves original writing and ink',async()=>{const h=harness();await h.submit('idea-capture',{title:'New project',body:'Original thought'});h.state.ink['1']=[{tool:'pen',points:[{x:.2,y:.3,p:.5}]}];h.state.tasks.push({id:'existing',matrixWeek:'2026-10-05',importance:'high',effort:'high',anchorActive:true});await h.submit('idea-ignite',{title:'First practical step',date:'2026-10-07',destination:'matrix',effort:'high',importance:'high'},'1');assert.equal(h.state.tasks[1].anchorActive,false);assert.equal(h.state.notes[0].ideaStatus,'ignited');assert.equal(h.state.entries['note:1'],'Original thought');assert.equal(h.state.ink['1'].length,1);await h.submit('idea-ignite',{title:'Duplicate',date:'2026-10-07',destination:'matrix'},'1');assert.equal(h.state.tasks.length,2);});
test('calendar ignition validates times before consuming the parked idea',async()=>{const h=harness();await h.submit('idea-capture',{title:'Try something',body:''});await h.submit('idea-ignite',{title:'Experiment',date:'2026-10-08',destination:'calendar',time:'10:00',endTime:'09:00'},'1');assert.equal(h.state.events.length,0);assert.equal(h.state.notes[0].ideaStatus,'parked');await h.submit('idea-ignite',{title:'Experiment',date:'2026-10-08',destination:'calendar',time:'10:00',endTime:'10:30'},'1');assert.equal(h.state.events[0].ideaId,'1');assert.equal(h.state.events[0].time,'10:00');});
