import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
function harness(entries={}){const ctx={Gym:{createGymController:()=>({})},confirmAction:()=>{},snapshot:()=>{},download:()=>{},PackGo:{createPackingController:()=>({})},document:{addEventListener:()=>{}},id:()=>'',openModal:()=>{},closeModal:()=>{},state:{entries},entry:k=>entries[k]||'',esc:String,ruled:(key,label)=>`<textarea data-entry="${key}">${entries[key]||''}</textarea>`,save:()=>{},render:()=>{},toast:()=>{}};vm.createContext(ctx);vm.runInContext(source.match(/const plannerTemplates=.*;/)[0]+'\n'+source.match(/const plannerFlows=.*;/)[0]+'\n'+source.match(/const plannerCategories=.*;/)[0]+'\n'+source.match(/const plannerRelated=.*;/)[0]+'\n'+source.match(/const plannerIcons=.*;/)[0]+"\nlet plannerPage='old',plannerCategory=null,plannerSearch='',plannerPinned=false;\n"+source.slice(source.indexOf('function plannerRecords()'),source.indexOf("document.addEventListener('input',e=>{if(e.target.id==='planner-search')")),ctx);return ctx;}
test('all 42 forms have distinct ordered workflows and retain existing answers under original labels',()=>{const entries={'form:old:type':'normal-day','form:old:title':'My routine','form:old:section-0':'Existing personal writing','form:old:cell-0-0':'Existing row'};const original=JSON.stringify(entries);const c=harness(entries);assert.equal(vm.runInContext('plannerTemplates.length',c),42);assert.equal(vm.runInContext('plannerTemplates.every(t=>plannerFlows[t.id]?.columns.length===4)',c),true);const html=vm.runInContext('renderPlanner()',c);assert.ok(html.includes('Your previous answers'));assert.ok(html.includes('Existing personal writing'));assert.ok(html.includes('Existing row'));assert.ok(html.includes('flow-cell-0-0'));assert.equal(JSON.stringify(entries),original);});
test('pinning, completing and archiving a form preserve writing and round-trip as string entries',()=>{const entries={'form:old:type':'holiday','form:old:flow-context':'Keep me','form:old:flow-cell-0-1':'Berlin'};const c=harness(entries);vm.runInContext("plannerClick({plannerPin:'old'});plannerClick({plannerDone:'0'});plannerClick({plannerRow:''});plannerClick({plannerArchive:'old'});",c);assert.equal(entries['form:old:pinned'],'yes');assert.equal(entries['form:old:flow-done-0'],'yes');assert.equal(entries['form:old:rows'],'5');assert.equal(entries['form:old:archived'],'yes');assert.equal(entries['form:old:flow-context'],'Keep me');assert.equal(entries['form:old:flow-cell-0-1'],'Berlin');const restored=JSON.parse(JSON.stringify(entries));assert.deepEqual(restored,entries);vm.runInContext("plannerPinned=true;plannerPage=null",c);assert.ok(!vm.runInContext('renderPlanner()',c).includes('data-planner-open="old"'));});

test('every existing form has exactly one primary section and related forms stay single copies',()=>{const c=harness();assert.equal(vm.runInContext('plannerCategories.length',c),9);assert.equal(vm.runInContext('plannerTemplates.every(t=>plannerCategories.filter(c=>c.templates.includes(t.id)).length===1)',c),true);assert.equal(vm.runInContext('new Set(plannerTemplates.map(t=>t.id)).size',c),42);vm.runInContext("plannerCategory='money';plannerSearch=''",c);const html=vm.runInContext('plannerCatalogue()',c);assert.equal((html.match(/data-planner-template="holiday"/g)||[]).length,1);assert.ok(html.includes('household-budget'));});
test('search crosses sections and saved answers are unaffected by navigation',()=>{const entries={'form:old:type':'normal-day','form:old:title':'Keep routine','form:old:flow-context':'Original writing'};const before=JSON.stringify(entries),c=harness(entries);vm.runInContext("plannerCategory='money';plannerSearch='packing'",c);const html=vm.runInContext('plannerCatalogue()',c);assert.ok(html.includes('data-planner-template="pack-go"'));assert.ok(html.includes('across all sections'));vm.runInContext("plannerClick({plannerCategory:'travel'});plannerClick({plannerCategories:''});",c);assert.equal(vm.runInContext('plannerCategory',c),null);assert.equal(JSON.stringify(entries),before);});
